apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: my-apps
        image: us.gcr.io/project1-vois/prog:1
        envFrom:
        - configMapRef:
            name: my-app-cm
